# Site
#repository: sproogen/resume-theme
#favicon: images/favicon.ico

# Personal info
name: Rishabh Jain
title: Research Engineer
#email: rishabh.jain@nrel.gov
website: risjain.github.io

# Social links
#twitter_username: facespics
github_username:  risjain
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: risjain
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0001-5457-3929

additional_links:
- title: Google Scholar
  icon: https://scholar.google.com/citations/images/avatar_scholar_128.png
  url: https://scholar.google.com/citations?user=8YvHALEAAAAJ
- title: Email
  icon: https://github.com/risjain/risjain.github.io/blob/master/images/email.png
  url: https://docs.google.com/forms/d/e/1FAIpQLSd8ffk7m9HMW_GGiCFigIL5msEmNklDI0OezFy8e0E2lEocqg/formResponse


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
link: https://risjain.github.io
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Rishabh. I am a research engineer at the National Renewable Energy Laboratory in the Power Systems Engineering Center. I am leading multiple research projects focused on transportation electrification, sustainable grid integration of renewables, networked microgrids, and market opportunities for grid support services. My expertise is in quasi-steady-state and real-time hardware-in-the-loop power system modeling, grid protection from faults, and, control, design and operation of microgrids. 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Outreach and Interests
more_content: | # this will include new lines to allow paragraphs
  Outreach:
   - Reviewer : Publications in multiple prestigious journals including IEEE Transactions on Power Systems, Power Delivery, Sustainable Energy, IET Generation, and others} 
   - Facilitator : Assessing Quantum Computing Efforts for Next Generation Energy Research
   - NREL Point-of-Contact: IEEE Workshop on Quantum Computing Applications for Renewable Energy Systems
  
  R&D : 
   - Research opportunities for residential and commercial scale electrification of light/heavy duty vehicles
   - Protection of power systems with high renewable penetration
   - Quantum computing algorithms for applications in autonomous energy systems

  Professional Interests :
   - Membership : Institute of Electrical and Electronics Engineers (IEEE), International Council for Large Electric Systems (CIGRE)
   - Toastmasters - Active Member, Secretary and Treasurer (2020)


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
